apiVersion: v1
kind: Pod
metadata:
  name: exit-code-139-simulation
spec:
  containers:
  - name: exit-code-134
    image: python:alpine  # Use a lightweight Python image
    command: ["python", "-c", "import os; os.abort()"]
