apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv-static
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-1234567890 # Replace with your actual EBS volume ID
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: In
              values:
                - us-east-1a # Replace with the actual availability zone of your EBS volume