apiVersion: v1
kind: Pod
metadata:
  name: stress-pod
spec:
  containers:
  - name: stress
    image: polinux/stress
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    args:
    - "--cpu"
    - "1"
    - "--vm"
    - "1"
    - "--vm-bytes"
    - "128M"
    - "--timeout"
    - "600s"
