apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv-bucket1
spec:
  capacity:
    storage: 1200Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  claimRef:
    namespace: default
    name: s3-pvc-bucket1
  mountOptions:
    - allow-delete
    - region us-east-1
  csi:
    driver: s3.csi.aws.com
    volumeHandle: s3-csi-driver-volume-1
    volumeAttributes:
      bucketName: mountpoint-s3-csi-driver-testing-bucket-1 # Replace with your S3 bucket name
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-pvc-bucket1
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1200Gi
  volumeName: s3-pv-bucket1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv-bucket2
spec:
  capacity:
    storage: 1200Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  claimRef:
    namespace: default
    name: s3-pvc-bucket2
  mountOptions:
    - allow-delete
    - region us-east-1
  csi:
    driver: s3.csi.aws.com
    volumeHandle: s3-csi-driver-volume-2
    volumeAttributes:
      bucketName: mountpoint-s3-csi-driver-testing-bucket-2 # Replace with your S3 bucket name
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-pvc-bucket2
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1200Gi
  volumeName: s3-pv-bucket2
---
apiVersion: v1
kind: Pod
metadata:
  name: s3-multi-bucket-app
spec:
  containers:
    - name: app
      image: ubuntu
      command: ["/bin/sh"]
      args:
        - "-c"
        - |
          echo 'Data for bucket 1' >> /data1/$(date -u).txt
          echo 'Data for bucket 2' >> /data2/$(date -u).txt
          tail -f /dev/null
      volumeMounts:
        - name: storage-bucket1
          mountPath: /data1
        - name: storage-bucket2
          mountPath: /data2
  volumes:
    - name: storage-bucket1
      persistentVolumeClaim:
        claimName: s3-pvc-bucket1
    - name: storage-bucket2
      persistentVolumeClaim:
        claimName: s3-pvc-bucket2