apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-shared-pv
spec:
  capacity:
    storage: 1200Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  claimRef:
    namespace: default
    name: s3-shared-pvc
  mountOptions:
    - allow-delete
    - region us-east-1
  csi:
    driver: s3.csi.aws.com
    volumeHandle: s3-shared-volume
    volumeAttributes:
      bucketName: mountpoint-s3-csi-driver-testing-bucket # Replace with your S3 bucket name
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-shared-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1200Gi
  volumeName: s3-shared-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-shared-app
  labels:
    app: s3-shared-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: s3-shared-app
  template:
    metadata:
      labels:
        app: s3-shared-app
    spec:
      containers:
      - name: s3-app
        image: ubuntu
        command: ["/bin/sh"]
        args:
          - "-c"
          - |
            POD_NAME=$(hostname)
            echo "Hello from pod $POD_NAME at $(date -u)" >> /data/$POD_NAME-$(date -u).txt
            tail -f /dev/null
        volumeMounts:
        - name: shared-storage
          mountPath: /data
        ports:
        - containerPort: 80
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: s3-shared-pvc