apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
  #App container
  - name: nginx-container
    image: nginx:latest
    ports:
      - containerPort: 80
  #This is extra container
  ephemeralContainers:
  - name: ephemeral-container
    image: busybox
    targetContainerName: nginx-container
    securityContext:
      privileged: true