apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim-static
spec:
  storageClassName: "" # Explicitly empty to prevent default StorageClass assignment
  volumeName: test-pv-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi