apiVersion: v1
kind: Pod
metadata:
  name: static-pod
  labels:
    app: static-pod-demo
spec:
  containers:
  - name: my-container
    image: nginx
    ports:
      - containerPort: 80
    livenessProbe:
      httpGet:
        path: /healthz
        port: 80
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 2
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /readiness
        port: 80
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 2
      failureThreshold: 3


# This yaml file will create a static pod with liveliness and readiness probes you have to put this file in directory: /var/lib/kubelet (the directory where static pods defines)
#once you put this file in your node's dirctory as above mentioned kubelet will start a static pod with liveliness and readiness probes