apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app2
  namespace: default
spec:
  interval: 15m
  path: "./fluxcd/repos/infra-repo/apps/app2/deploy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: app2