# storageclass-static.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-static-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
reclaimPolicy: Retain
volumeBindingMode: Immediate