# .github/workflows/docker-build-push.yaml
name: K8s-Tools Kubectl - Docker Build & Manifest Update

on:
  workflow_dispatch:
    # inputs:
    #   bump-type:
    #     description: 'Version bump type'
    #     required: true
    #     default: 'v1.29.3'
    #     type: choice
    #     options:
    #     - 1.29.3
    #     - 1.29.2
  push:
    branches:
      - main
      - fluxcd
    paths:
      - 'dockerfiles/k8s-toolbox/kubectl/Dockerfile'

jobs:
  build-push-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (with all branches)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: fluxcd

      - name: Prepare version
        id: prep
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            BUILD_IMAGE=true
          else
            VERSION=${GITHUB_SHA::8}
            BUILD_IMAGE=true
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "IMAGE=anvesh35/k8s-tools:v1.29.3-$VERSION" >> $GITHUB_ENV
          echo "BUILD_IMAGE=$BUILD_IMAGE" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        if: env.BUILD_IMAGE == 'true'
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        if: env.BUILD_IMAGE == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        if: env.BUILD_IMAGE == 'true'
        uses: docker/build-push-action@v4
        with:
          context: dockerfiles/k8s-toolbox/kubectl/
          file: dockerfiles/k8s-toolbox/kubectl/Dockerfile
          push: true
          tags: ${{ env.IMAGE }}
          platforms: linux/amd64,linux/arm64
