# .github/workflows/docker-build-push.yaml
name: MicroServices Demo | AdService - Docker Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to use for the Docker image'
        required: true
        default: 'v1.0.0'
        type: choice
        options:
        - v1.0.0
        - v1.0.1
        - v1.0.2
  push:
    branches:
      - main
      - feature/docs_update
      - feature/microservicesdemo
    paths:
      - 'projects/microservices-demo/src/adservice/Dockerfile'

jobs:
  build-push-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (with all branches)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: feature/microservicesdemo

      - name: Prepare version
        id: prep
        run: |
          if [[ ${{ github.event_name }} == 'workflow_dispatch' ]]; then
            VERSION=${{ github.event.inputs.version }}
          else
            VERSION=${GITHUB_SHA::8}
          fi
          BUILD_IMAGE=true
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "IMAGE=anvesh35/microservices-demo-adservice:$VERSION" >> $GITHUB_ENV
          echo "LATESTIMAGE=anvesh35/microservices-demo-adservice:latest" >> $GITHUB_ENV
          echo "BUILD_IMAGE=$BUILD_IMAGE" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        if: env.BUILD_IMAGE == 'true'
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        if: env.BUILD_IMAGE == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push k8s-tools Docker image
        if: env.BUILD_IMAGE == 'true'
        uses: docker/build-push-action@v4
        with:
          context: projects/microservices-project/src/adservice/
          file: projects/microservices-project/src/adservice/Dockerfile
          push: true
          tags: ${{ env.IMAGE }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            VERSION=${{ env.VERSION }}
      